# Generated by Django 5.2.17 on 2026-09-30 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakeLink',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(max_length=40, unique=True)),
                ('amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(default='created', max_length=20)),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('customer', models.JSONField(default=dict)),
                ('notes', models.JSONField(default=dict)),
                ('expire_by', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FakePayment',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=40)),
                ('amount', models.PositiveBigIntegerField()),
                ('amount_refunded', models.PositiveBigIntegerField(default=0)),
                ('method', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('fee', models.PositiveBigIntegerField(default=0)),
                ('tax', models.PositiveBigIntegerField(default=0)),
                ('notes', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField()),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sandbox.fakelink')),
            ],
        ),
        migrations.CreateModel(
            name='FakeRefund',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField()),
                ('receipt', models.CharField(blank=True, max_length=64)),
                ('notes', models.JSONField(default=dict)),
                ('status', models.CharField(default='processed', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sandbox.fakepayment')),
            ],
        ),
    ]
