# Generated by Django 5.2.17 on 2026-09-30 13:33

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('subtotal_paise', models.PositiveBigIntegerField(default=0)),
                ('discount_paise', models.PositiveBigIntegerField(default=0)),
                ('tax_paise', models.PositiveBigIntegerField(default=0)),
                ('total_paise', models.PositiveBigIntegerField(default=0)),
                ('amount_paid_paise', models.PositiveBigIntegerField(default=0)),
                ('amount_refunded_paise', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.centre')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.staff')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField(help_text='Starting year, e.g. 2026 for FY 26-27')),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price_paise', models.PositiveBigIntegerField()),
                ('gst_rate_bps', models.PositiveIntegerField(help_text='GST in basis points: 1800 = 18%')),
                ('is_active', models.BooleanField(default=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='accounts.centre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('qty', models.PositiveIntegerField()),
                ('unit_price_paise', models.PositiveBigIntegerField()),
                ('gst_rate_bps', models.PositiveIntegerField()),
                ('line_total_paise', models.PositiveBigIntegerField(help_text='qty x unit price, before discount')),
                ('discount_paise', models.PositiveBigIntegerField(default=0, help_text='Share of invoice discount')),
                ('tax_paise', models.PositiveBigIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.service')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['centre', 'status', 'created_at'], name='billing_inv_centre__26e021_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_paise__lte', models.F('subtotal_paise'))), name='invoice_discount_within_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_paise', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal_paise'), '-', models.F('discount_paise')), '+', models.F('tax_paise')))), name='invoice_total_consistent'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_refunded_paise__lte', models.F('amount_paid_paise'))), name='invoice_refunds_within_paid'),
        ),
        migrations.AddConstraint(
            model_name='invoicecounter',
            constraint=models.UniqueConstraint(fields=('centre', 'fiscal_year'), name='uniq_counter_per_centre_fy'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('centre', 'name'), name='uniq_service_name_per_centre'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('gst_rate_bps__lte', 10000)), name='service_gst_rate_at_most_100pct'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', 1)), name='invoice_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total_paise', django.db.models.expressions.CombinedExpression(models.F('qty'), '*', models.F('unit_price_paise')))), name='invoice_item_line_total_consistent'),
        ),
    ]
