# Generated by Django 5.2.17 on 2026-09-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.payment'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit_paise', 0), ('credit_paise__gt', 0)), models.Q(('credit_paise', 0), ('debit_paise__gt', 0)), _connector='OR'), name='ledger_one_sided_entry'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'payment')), fields=('payment', 'entry_type'), name='uniq_ledger_credit_per_payment'),
        ),
    ]
