# Generated by Django 5.2.17 on 2026-09-30 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('ledger', '0003_append_only_trigger'),
        ('payments', '0002_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.refund'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'refund')), fields=('refund', 'entry_type'), name='uniq_ledger_debit_per_refund'),
        ),
    ]
