# Generated by Django 5.2.17 on 2026-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('raw_payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(condition=models.Q(('processed_at__isnull', True)), fields=['received_at'], name='webhook_unprocessed_idx')],
            },
        ),
    ]
