# Generated by Django 5.2.17 on 2026-09-30 14:05

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The business day being reconciled (IST)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('overpaid', 'Invoice overpaid'), ('amount_mismatch', 'Amount mismatch'), ('payment_on_closed_invoice', 'Payment on closed invoice'), ('unmatched_payment', 'Payment not linked to an invoice'), ('missing_locally', 'Captured at gateway, missing locally'), ('missing_at_gateway', 'Recorded locally, missing at gateway'), ('status_mismatch', 'Status mismatch'), ('invoice_drift', 'Invoice paid amount drift'), ('settlement_mismatch', 'Settlement mismatch'), ('stuck_event', 'Webhook event stuck'), ('refund_orphaned', 'Refund for unknown payment')], max_length=40)),
                ('gateway_ref', models.CharField(help_text='e.g. pay_XXXX, plink_XXXX, event id', max_length=64)),
                ('local_ref', models.CharField(blank=True, max_length=64)),
                ('expected_paise', models.BigIntegerField(blank=True, null=True)),
                ('actual_paise', models.BigIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='billing.invoice')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='reconciliation.reconciliationrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('kind', 'gateway_ref'), name='uniq_open_issue_per_kind_ref')],
            },
        ),
    ]
