# Generated by Django 5.2.17 on 2026-09-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.PositiveBigIntegerField()),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('reference_id', models.CharField(max_length=40, unique=True)),
                ('gateway_link_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('short_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending (gateway not called yet)'), ('created', 'Link active'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Gateway call failed')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.staff')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='billing.invoice')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_payment_id', models.CharField(max_length=40, unique=True)),
                ('gateway_order_id', models.CharField(blank=True, max_length=40)),
                ('amount_paise', models.PositiveBigIntegerField()),
                ('method', models.CharField(blank=True, help_text='upi, card, netbanking, ...', max_length=20)),
                ('status', models.CharField(choices=[('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed')], max_length=20)),
                ('fee_paise', models.PositiveBigIntegerField(default=0, help_text='Gateway fee incl. GST')),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentattempt')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'captured'), _negated=True), ('captured_at__isnull', False), _connector='OR'), name='payment_captured_has_timestamp')],
            },
        ),
    ]
